[tool.poetry]
name = "norfetch"
version = "0.1.0"
description = "norweigan fetch tool"
authors = ["balkenix"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
